/*
 * CityGeometry.h
 *
 *  Created on: Apr 21, 2019
 *      Author: developer
 */

#ifndef CITYGEOMETRY_H_
#define CITYGEOMETRY_H_

#include "RobotGeometry.h"

#define INNER_DIST_BETWEEN_PLOTS_MM 546.1

#define LEAD_ROADS_LENGTH (31.5 *  IN_TO_MM) + (INNER_DIST_BETWEEN_PLOTS_MM / 2)


#define BUILDING_LENGTH (10 * IN_TO_MM)
#define LENGTH_BETWEEN_TO_INTERSECTIONS (INNER_DIST_BETWEEN_PLOTS_MM) + BUILDING_LENGTH

#define INITIAL_Y_MOVE 200
#define START_TO_INTESECTION_DIST 1550
#define FINAL_ROAD_DIST (INNER_DIST_BETWEEN_PLOTS_MM / 2)

#endif /* CITYGEOMETRY_H_ */
